/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chap4;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Natth
 */
public class CountDownTimerGUI extends javax.swing.JFrame {

    int min, sec, hour, hour1, min1, sec1;
    Timer timer;
    boolean isStop = false;

    public CountDownTimerGUI() {
        initComponents();
        for (int i = 0; i <= 24; i++) {
            if (i < 10) {
                cbxHour.addItem("0" + i);
            } else {
                cbxHour.addItem("" + i);
            }
        }
        for (int i = 0; i < 60; i++) {
            if (i < 10) {
                cbxMinute.addItem("0" + i);
            } else {
                cbxMinute.addItem("" + i);
            }
        }
        for (int i = 0; i < 60; i++) {
            if (i < 10) {
                cbxSec.addItem("0" + i);
            } else {
                cbxSec.addItem("" + i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMinute = new javax.swing.JLabel();
        lblSec = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        cbxMinute = new javax.swing.JComboBox<>();
        cbxSec = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxHour = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn30 = new javax.swing.JButton();
        btn1h = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 255));
        jLabel1.setText("Count Down Timer By Natthira");

        lblMinute.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        lblMinute.setForeground(new java.awt.Color(51, 51, 255));
        lblMinute.setText("00 ");

        lblSec.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        lblSec.setForeground(new java.awt.Color(51, 51, 255));
        lblSec.setText("00");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText(":");

        btnStart.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        cbxMinute.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbxMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMinuteActionPerformed(evt);
            }
        });

        cbxSec.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbxSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSecActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Minute");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Second");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chap4/clo.jpg"))); // NOI18N

        cbxHour.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbxHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHourActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Hour");

        lblHour.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        lblHour.setForeground(new java.awt.Color(51, 51, 255));
        lblHour.setText("00");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText(":");

        btn30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn30.setText("30 min");
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });

        btn1h.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn1h.setText("1 hour");
        btn1h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1hActionPerformed(evt);
            }
        });

        btn15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn15.setText("15 min");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbxHour, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn30)
                                        .addGap(12, 12, 12)
                                        .addComponent(btn1h))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(cbxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(btnStart)
                                        .addGap(17, 17, 17)))
                                .addGap(18, 18, 18)))
                        .addComponent(btnStop))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHour)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMinute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSec)
                        .addGap(81, 81, 81)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinute)
                            .addComponent(lblSec)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(lblHour)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1h)
                    .addComponent(btn15)
                    .addComponent(btn30))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStop)
                        .addComponent(btnStart))
                    .addComponent(cbxHour, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btnStart.setEnabled(false);
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (isStop) {
                    min = min1;
                    sec = sec1;
                    hour = hour1;

                    isStop = false;
                }
                if (sec < 1) {
                    sec = 60;
                    min--;
                }
                if (min < 0 ){
                    min=59;
                    hour--;
                }
                
                if (hour < 0) {
                    JOptionPane.showMessageDialog(rootPane, "จับเวลาเสร็จละโว้ย");
                    hour = 0;
                    min = 0;
                    sec = 0;
                    timer.stop();
                    btnStart.setEnabled(true);
                } else {
                    sec--;
                }
                if (sec < 10) {
                    lblSec.setText("0" + sec);
                } else {
                    lblSec.setText("" + sec);
                }
                if (min < 10) {
                    lblMinute.setText("0" + min);
                } else {
                    lblMinute.setText("" + min);
                }
                if(hour < 10){
                    lblHour.setText("0"+hour);
                }else{
                     lblHour.setText(""+hour);
                }

            }
        });
        timer.start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void cbxMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMinuteActionPerformed
        lblMinute.setText("" + cbxMinute.getSelectedItem());
        min = Integer.parseInt(lblMinute.getText());
    }//GEN-LAST:event_cbxMinuteActionPerformed

    private void cbxSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSecActionPerformed
        lblSec.setText("" + cbxSec.getSelectedItem());
        sec = Integer.parseInt(lblSec.getText());
    }//GEN-LAST:event_cbxSecActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        min1 = min;
        sec1 = sec;
        hour1 = hour;
        isStop = true;
        timer.stop();
        btnStart.setEnabled(true);
    }//GEN-LAST:event_btnStopActionPerformed

    private void cbxHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHourActionPerformed
        lblHour.setText("" + cbxHour.getSelectedItem());
        hour = Integer.parseInt(lblHour.getText());
    }//GEN-LAST:event_cbxHourActionPerformed

    private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed
        min=30;
        lblMinute.setText("" + min);
    }//GEN-LAST:event_btn30ActionPerformed

    private void btn1hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1hActionPerformed
        hour=1;
        lblHour.setText("0" + hour);
    }//GEN-LAST:event_btn1hActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        min=15;
        lblMinute.setText("" + min);
    }//GEN-LAST:event_btn15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountDownTimerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn1h;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox<String> cbxHour;
    private javax.swing.JComboBox<String> cbxMinute;
    private javax.swing.JComboBox<String> cbxSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblMinute;
    private javax.swing.JLabel lblSec;
    // End of variables declaration//GEN-END:variables
}
