/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Natth
 */
public class LetterPostShop extends javax.swing.JFrame {

    /**
     * Creates new form LetterPostShop
     */
    public LetterPostShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdbNomal = new javax.swing.JRadioButton();
        rdbRegis = new javax.swing.JRadioButton();
        rdbEMS = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarOutput = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("ส่งจดหมาย");

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel2.setText("ประเภทจดหมาย");

        buttonGroup1.add(rdbNomal);
        rdbNomal.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        rdbNomal.setText("ธรรมดา");

        buttonGroup1.add(rdbRegis);
        rdbRegis.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        rdbRegis.setText("ลงทะเบียน");

        buttonGroup1.add(rdbEMS);
        rdbEMS.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        rdbEMS.setText("EMS");

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel3.setText("น้ำหนักจดหมาย (g)");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        btnTotal.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnTotal.setText("คำนวณราคา");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        tarOutput.setColumns(20);
        tarOutput.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tarOutput.setRows(5);
        jScrollPane1.setViewportView(tarOutput);

        btnClear.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(rdbNomal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbRegis)
                .addGap(18, 18, 18)
                .addComponent(rdbEMS)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnClear)
                        .addGap(124, 124, 124)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtPrice)
                .addGap(18, 18, 18)
                .addComponent(btnTotal)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdbNomal)
                    .addComponent(rdbRegis)
                    .addComponent(rdbEMS))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        String Price =txtPrice.getText();
        if(Price.length()>0){
        if(rdbNomal.isSelected()){
        String weightS=txtPrice.getText();
        int weight = Integer.valueOf(weightS);
        int weightre = 0;
                weightre = Normal(weight, weightre);
        weightS = String.valueOf(weightre);
        tarOutput.setText("Normal Letter Service Price : "+ weightS +" Bath");
    }else if(rdbRegis.isSelected()){
        String weightS=txtPrice.getText();
        int weight = Integer.valueOf(weightS);
        int weightre = 0;
        weightre = Normal(weight, weightre);
        weightre+=13;
        weightS = String.valueOf(weightre);
        tarOutput.setText("Register Letter Service Price : "+ weightS +" Bath");
    }else if(rdbEMS.isSelected()){
        String weightS=txtPrice.getText();
        int weight = Integer.valueOf(weightS);
        int weightre = 0;
        if (weight <= 20) {
            weightre = 27;
        } else if (weight <= 100) {
            weightre = 32;
        } else if (weight <= 250) {
            weightre = 37;
        } else if (weight <= 500) {
            weightre = 47;
        } else if (weight <= 1000) {
            weightre = 62;
        } else if (weight <= 2500) {
            weightre = 77;
        }
        weightS = String.valueOf(weightre);
        tarOutput.setText("EMS Letter Service Price : "+ weightS +" Bath");
    }}
    }//GEN-LAST:event_btnTotalActionPerformed

    public int Normal(int weight, int weightre) {
        if (weight <= 20) {
            weightre = 3;
        } else if (weight <= 100) {
            weightre = 5;
        } else if (weight <= 250) {
            weightre = 9;
        } else if (weight <= 500) {
            weightre = 15;
        } else if (weight <= 1000) {
            weightre = 25;
        } else if (weight <= 2500) {
            weightre = 25;
        }
        return weightre;
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Exit?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        buttonGroup1.clearSelection();
        tarOutput.setText("");
        txtPrice.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LetterPostShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbEMS;
    private javax.swing.JRadioButton rdbNomal;
    private javax.swing.JRadioButton rdbRegis;
    private javax.swing.JTextArea tarOutput;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
